### ISSUE TITLE
Error at Table functions- httpx.ConnectError: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by pehzet** [supabase-community/supabase-py#243]
Hey,

I just started using supabase with the aim to store some experiment data in the db.  When I try to execute any kind of supabase.table-functions I get the httpx error "httpx.ConnectError: [Errno 11001] getaddrinfo failed" (see below).
The table exists, and it got some manually added dummy data.

**My stats:**
python 3.7.7 (but also in 3.10.4) Win10 x64
supabase 0.5.8

**The Code:**

```
import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()
url: str = os.getenv("SUPABASE_URL")
key: str = os.getenv("SUPABASE_KEY")

supabase: Client = create_client(url, key)
data = supabase.table("experiments").select("*").execute()
print(data)
```

**The error:**
Traceback (most recent call last):
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpcore\backends\sync.py", line 83, in connect_tcp
    address, timeout, source_address=source_address
  File "C:\Python\python377-64\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python\python377-64\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpx\_transports\default.py", line 204, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpcore\_sync\connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpcore\backends\sync.py", line 83, in connect_tcp
    address, timeout, source_address=source_address

  File "C:\Python\python377-64\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\code\supabase-tmp\tmp.py", line 18, in <module>
    data = supabase.table("countries").select("*").execute()
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\postgrest\_sync\request_builder.py", line 58, in execute
    headers=self.headers,
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpx\_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpx\_client.py", line 893, in send
    history=[],
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpx\_client.py", line 920, in _send_handling_auth
    history=history,
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpx\_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpx\_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpx\_transports\default.py", line 204, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Python\python377-64\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\code\supabase-tmp\supaenv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

**Comment by anand2312** [comment]
This doesn't seem to be an issue with supabase-py itself, are you sure you're passing in the right project URL and api key?
Stackoverflow also seems to suggest it could be an issue with some network proxy settings 🤔

**Comment by pehzet** [comment]
It was a mistake on my side... Sorry for that. I closed the issue.
It works fine now. :)
