### ISSUE TITLE
Error when running this code

### ISSUE THREAD

**Issue by cmarshalldev** [supabase-community/supabase-py#280]
When i run this code i get an error

```
import os
from supabase import create_client, Client
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)
# Create a random user login email and password.
random_email: str = "cam@example.com"
random_password: str = "9696"
user = supabase.auth.sign_up(email=random_email, password=random_password)
```

here's the error message

```
Traceback (most recent call last):
  File "C:\Users\Camer\AppData\Local\Programs\Python\Python310\lib\site-packages\gotrue\helpers.py", line 16, in check_response
    response.raise_for_status()       
  File "C:\Users\Camer\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_models.py", line 1508, in 
raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://gcaycwdskjdsfqvrtdqh.supabase.co/auth/v1/signup'
For more information check: https://httpstatuses.com/422

During handling of the above exception, another exception occurred:

Traceback (most recent call last):    
  File "C:\Users\Camer\Cams-Stuff\coding\pyTesting\main.py", line 11, in <module>
    user = supabase.auth.sign_up(email=random_email, password=random_password)
  File "C:\Users\Camer\AppData\Local\Programs\Python\Python310\lib\site-packages\gotrue\_sync\client.py", line 129, in sign_up
    response = self.api.sign_up_with_email(
  File "C:\Users\Camer\AppData\Local\Programs\Python\Python310\lib\site-packages\gotrue\_sync\api.py", line 140, in sign_up_with_email
    return SessionOrUserModel.parse_response(response)
  File "C:\Users\Camer\AppData\Local\Programs\Python\Python310\lib\site-packages\gotrue\types.py", line 26, in parse_response
    check_response(response)
  File "C:\Users\Camer\AppData\Local\Programs\Python\Python310\lib\site-packages\gotrue\helpers.py", line 18, in check_response
    raise APIError.from_dict(response.json())
gotrue.exceptions.APIError
```

**Comment by J0** [comment]
Hey @cmarshalldev 

Thanks for the query and apologies for the delay. For security reasons, passwords need to be longer than 6 characters -- do try again with a longer password and let us know if you're facing any other issues!

Joel
