### ISSUE TITLE
JSONDecodeError is raised when db operations return None (void)

### ISSUE THREAD

**Issue by Ceravoux** [supabase-community/supabase-py#341]
**JSONDecodeError when db operations return None (void)**
I'm not completely certain but I presume that this is due to json.loads in httpx

**To Reproduce**
For example we have an rpc that returns void
`create function increment(row_id int)
returns void as
$$
  update table_name
  set field_name = field_name + 1
  where id = row_id;
$$
language sql volatile;`
and calling it by `data = supabase.rpc("increment", {"row_id": 42}).execute()`
will raise json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0).

Here's the traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\postgrest\_sync\request_builder.py", line 62, in execute
    a = APIResponse.from_http_request_response(r)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\postgrest\base_request_builder.py", line 154, in from_http_request_response
    data = request_response.json()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode        
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Expected behavior**
return an empty list or other

**Comment by J0** [comment]
transferring to `postgrest-py` for better tracking
