### ISSUE TITLE
Unable initialize a new Supabase client using the create_client() method

### ISSUE THREAD

**Issue by 0x-Legend** [supabase-community/supabase-py#493]
**Describe the bug**
Unable initialize a new Supabase client using the create_client() method. Error says supabase_url is required even though I have provided it, along with the key.

**To Reproduce**
1. Go to 'https://supabase.com/docs/reference/python/initializing'
2. Scroll down to 'Initializing'
3. Run the code locally with your own url and key

**Expected behavior**
Code to run with no errors and complete with:
Process finished with exit code 0

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [MacOS 13.4.1]
 - Browser [PyCharm 2022.1.4 (Professional Edition)]
 - Version [Build #PY-221.6008.17, built on July 20, 2022]

**Additional context**
Output:
/Users/anon/Desktop/LP/pythonProject/venv/bin/python "/Users/anon/Desktop/LP/pythonProject/supabase client.py"
Traceback (most recent call last):
  File "/Users/anon/Desktop/LP/pythonProject/supabase client.py", line 6, in <module>
    supabase: Client = create_client(url, key)
  File "/Users/anon/Desktop/LP/pythonProject/venv/lib/python3.10/site-packages/supabase/client.py", line 248, in create_client
    return Client(supabase_url=supabase_url, supabase_key=supabase_key, options=options)
  File "/Users/anon/Desktop/LP/pythonProject/venv/lib/python3.10/site-packages/supabase/client.py", line 45, in __init__
    raise SupabaseException("supabase_url is required")
supabase.client.SupabaseException: supabase_url is required

Process finished with exit code 1

**Comment by 0x-Legend** [comment]
Not sure if the documentation is wrong, but removing os worked

**Before:**
```Python
import os
from supabase import create_client, Client

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)
```

**After**
```Python
from supabase import create_client, Client

url: str = "SUPABASE_URL"
key: str = "SUPABASE_KEY"
supabase: Client = create_client(url, key)
```
