### ISSUE TITLE
Test failures on Python 3.12

### ISSUE THREAD

**Issue by tinvaan** [supabase-community/supabase-py#717]
# Bug report

## Describe the bug

Tests are broken against Python 3.12.
```AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?```

## To Reproduce

Run test script in a python 3.12 environment.

## Expected behavior

Tests should not fail.

## Logs

```bash
ERROR: invocation failed (exit code 1), logfile: /Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/log/py312-3.log
========================================================================== log start ===========================================================================
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 315, in run
    session = self.get_default_session(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
    self._session = self.enter_context(self._build_session(options))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 180, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 175, in <genexpr>
    matches = (
              ^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 594, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 168, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 136, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 103, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 179, in handle_pip_version_check
    session = self._build_session(
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 180, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 175, in <genexpr>
    matches = (
              ^
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 594, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 168, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 136, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 103, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "/Users/harish/Workspaces/oss/supabase/supabase-py/.tox/py312/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

## System information

- OS: macOS

## Additional context

Launched tests via a `tox` script. (see https://github.com/supabase-community/supabase-py/issues/696)

**Comment by silentworks** [comment]
The error here is an autoflake issue, if you upgrade to the latest `v2.3.0` of autoflake the error goes away.

**Comment by silentworks** [comment]
I've updated autoflake in the repo and the error should now be fixed.
