### ISSUE TITLE
User token overwrites admin API key

### ISSUE THREAD

**Issue by dericdesta** [supabase-community/supabase-py#806]
When a user is signed in using, e.g., `supabase.auth.sign_in_with_password({"email": ..., "password": ...})` the following function is called after the user token has been obtained:

https://github.com/supabase-community/supabase-py/blob/8468c2e665a3f5f27d456843e71d23f906c4f665/supabase/_sync/client.py#L254-L265 

Line 263 overwrites the admin API key `self.supabase_key` with the `session.access_token` of the currently signed in user and thus any admin auth call, e.g. `supabase.auth.admin.update_user_by_id(...)` will fail as the wrong Bearer token is used.
I think the currently logged in user should be ignored and the admin API key should be used when calling admin auth endpoints.

I'm on version `gotrue==2.1.0` and `supabase==2.4.6`.

**Comment by silentworks** [comment]
Please share your example code where this is happening because it would seem you are using a singleton in which case the effect you are getting is correct. Please provide example of your code where you are making these calls.

**Comment by dericdesta** [comment]
Hi @silentworks! Sure, here is a simple snippet reproducing the reported error.
The error can be avoided by using the `sign_out()` function right before the admin auth call, but I think this cannot be the fix.

```python
from supabase import create_client

supabase_url = "http://127.0.0.1:54321"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"

client = create_client(
    supabase_url=supabase_url,
    supabase_key=service_role_key
)

# print the Bearer token that is used
# here: service role key, (in header: apiKey == Authorization)
print(f"apiKey header after login: {client.options.headers['apiKey']}")
print(f"Authorization header before login: {client.options.headers['Authorization']}")

# login with a user with verified email
response = client.auth.sign_in_with_password(
    {"email": "user@acme.com", "password": "password"}
)
user = response.user

# print the Bearer token that is used
# here: user session token (in header: apiKey != Authorization)
print(f"apiKey header after login: {client.options.headers['apiKey']}")
print(f"Authorization header after login: {client.options.headers['Authorization']}")

# by uncommenting the following line, the user session token is removed
# and the service role key is used again in the next request
# client.auth.sign_out()

# try to modify the user with a admin call requiring the service role key
# this will fail throwing a 403 Forbidden, gotrue.errors.AuthApiError: User not allowed
# as the Authorization header is set to the user session token and not the service role key
user = client.auth.admin.update_user_by_id(
    uid=user.id, attributes={"user_metadata": {"some": "data"}}
)

```

I get the following output:
```
apiKey header after login: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
Authorization header before login: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

2024-05-23 11:04:52,461:INFO - HTTP Request: POST http://127.0.0.1:54321/auth/v1/token?grant_type=password "HTTP/1.1 200 OK"

apiKey header after login: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
Authorization header after login: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzE2NDU4NjkyLCJpYXQiOjE3MTY0NTUwOTIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTQzMjEvYXV0aC92MSIsInN1YiI6IjhkZGRhYjI4LTQyMGItNDIwMS04ZmRjLWMxOWZkZGIwY2U3MiIsImVtYWlsIjoidXNlckBhY21lLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsic29tZSI6ImRhdGEifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcxNjQ1NTA5Mn1dLCJzZXNzaW9uX2lkIjoiM2ZjNTkzNzQtYmJlYS00MjMzLTg4ZjYtNDMzOTkyZDZlYmUyIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.YuzmLxaEH9h-NZ61TL4NQCczX0mASRtly965qEY9apI

2024-05-23 11:04:52,469:INFO - HTTP Request: PUT http://127.0.0.1:54321/auth/v1/admin/users/8dddab28-420b-4201-8fdc-c19fddb0ce72 "HTTP/1.1 403 Forbidden"
Traceback (most recent call last):
  File "/Users/fmadesta/miniconda3/envs/smart-med/lib/python3.10/site-packages/gotrue/_sync/gotrue_base_api.py", line 113, in _request
    response.raise_for_status()
  File "/Users/fmadesta/miniconda3/envs/smart-med/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'http://127.0.0.1:54321/auth/v1/admin/users/8dddab28-420b-4201-8fdc-c19fddb0ce72'
For more information check: https://httpstatuses.com/403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fmadesta/projects/smart-med/backend/bug.py", line 34, in <module>
    user = client.auth.admin.update_user_by_id(
  File "/Users/fmadesta/miniconda3/envs/smart-med/lib/python3.10/site-packages/gotrue/_sync/gotrue_admin_api.py", line 145, in update_user_by_id
    return self._request(
  File "/Users/fmadesta/miniconda3/envs/smart-med/lib/python3.10/site-packages/gotrue/_sync/gotrue_base_api.py", line 118, in _request
    raise handle_exception(e)
gotrue.errors.AuthApiError: User not allowed
```

I think the `auth.admin` functions should always use the passed service role key independent of the logged in user. Or am I wrong?

**Comment by silentworks** [comment]
You are using a single client to perform two different things, you should instantiate a separate client for admin calls and for normal calls. This is how the library works, it's in line with how the JS library works too. You shouldn't be signing in a user with a service role key client.

Here is an example of how this code should be written:

```python
from supabase import create_client

supabase_url = "http://127.0.0.1:54321"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"

client = create_client(
    supabase_url=supabase_url,
    supabase_key=anon_key
)

admin_client = create_client(
    supabase_url=supabase_url,
    supabase_key=service_role_key
)

# login with a user with verified email
response = client.auth.sign_in_with_password(
    {"email": "user@acme.com", "password": "password"}
)
user = response.user

user = admin_client.auth.admin.update_user_by_id(
    uid=user.id, attributes={"user_metadata": {"some": "data"}}
)
```

**Comment by dericdesta** [comment]
That's what I figured. Thank you for clarifying.
